version: '{build}'
clone_depth: 1

image:
  - Ubuntu
  - Visual Studio 2017

platform:
  - x86
  - x64

matrix:
  exclude:
    - image: Ubuntu
      platform: x86

branches:
  only:
  - native-CI

before_build:
  - ps: "Get-ChildItem Env:"

build_script:
  - ps: ./build/build.ps1
   
artifacts:
  - path: "artifacts.zip"